Repository Minatoz997/OpenHands-Backend, pull requests merged in 2025-06, with the labels that each got.

#9 Fix
  openhands/server/app.py
  openhands/server/routes/manage_conversations.py
  openhands/server/routes/public.py
  openhands/server/services/conversation_service.py
Labels: Review effort 4/5, Possible security concern

#11 Hugginface fix
  DEPLOY_HUGGINGFACE.md
  Dockerfile_HF
  README_HF.md
  app_hf.py
Labels: Review effort 2/5

#12 Fix Hugging Face auto-deploy workflow
  .github/workflows/deploy.yaml
  CHANGELOG_AUTO_DEPLOY.md
  HUGGINGFACE_AUTO_DEPLOY.md
  space_config.yml
  test_hf_deploy.py
Labels: Possible security concern, Review effort 3/5

#18 🔧 Add HF Spaces memory storage and improved configuration
  app_hf.py
  openhands/server/app.py
  openhands/server/config/server_config.py
  openhands/server/routes/hf_spaces.py
  openhands/storage/secrets/memory_secrets_store.py
  openhands/storage/settings/memory_settings_store.py
Labels: Possible security concern, Review effort 3/5

#22 🎉 Complete OpenRouter + Novel Writing Integration - Production Ready
  COMPLETE_API_DOCUMENTATION.md
  FINAL_SUMMARY.md
  app_hf.py
  openhands/server/app.py
  openhands/server/routes/memory_conversation.py
  openhands/server/routes/novel_writing.py
  openhands/server/routes/openrouter_chat.py
  openhands/server/routes/openrouter_test.py
  openhands/server/routes/test_chat.py
  test_fixes.py
Labels: Review effort 4/5, Possible security concern

#30 🔧 FINAL FIX: Missing openhands_aci dependency (NO CONFLICTS)
  openhands/linter/__init__.py
  requirements.txt
Labels: Review effort 2/5

#32 🔧 COMPLETE FIX: All Missing Dependencies for HF Spaces
  openhands/runtime/impl/__init__.py
  requirements.txt
Labels: Review effort 3/5

#31 🔧 FINAL: Complete HF Spaces Deployment Fix - All Dependencies Resolved
  openhands/runtime/impl/__init__.py
  requirements.txt
Labels: Review effort 2/5

#35 🚀 FINAL FIX: Complete HF Spaces Backend66 Deployment Solution
  Dockerfile
  app.py
  requirements.txt
Labels: Review effort 4/5, Possible security concern

#38 🔥 COMPLETE FIX: All openhands_aci Import Errors Resolved!
  openhands/runtime/impl/cli/cli_runtime.py
  openhands/runtime/plugins/agent_skills/repo_ops/repo_ops.py
  openhands/runtime/utils/edit.py
  tests/runtime/test_llm_based_edit.py
Labels: Review effort 4/5, Possible security concern

#41 🔧 FINAL E2B FIX + COMPLETE EMERGENCY DOCUMENTATION ✅
  COMPLETE_AI_ASSISTANT_PROMPT.md
  openhands/runtime/impl/__init__.py
Labels: Review effort 2/5

#42 Fix docker import errors hf spaces
  Dockerfile_HF_Ultra_Minimal
  FINAL_SOLUTION_FOR_DOCKER_ERRORS.md
  openhands/agenthub/browsing_agent/__init__.py
  openhands/agenthub/visualbrowsing_agent/__init__.py
  openhands/runtime/__init__.py
  requirements_hf_minimal.txt
Labels: Review effort 4/5, Possible security concern
